version: "3.7"

services:
  app:
    user: vscode
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        USER_UID: 1000
        USER_GID: 1000
        # add any additional Debian OS dependencies installed using apt-get
        DEBIAN_DEPS: ""
         # add any npm dependencies installed using npm install
        NPM_DEPS: ""
        # add any python dependencies installed using pip3
        PIP_DEPS: ""
    # Uncomment the next two lines to expose the app on localhost:8000
    # ports:
    #   - "8000:8000"
    volumes:
      - ..:/workspace:cached
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/home/vscode/.ssh:ro
      - ~/.ssh:/root/.ssh:ro
      - /var/run/docker.sock:/var/run/docker-host.sock

  db:
    image: postgres
    restart: unless-stopped
    # Uncomment the next two lines to expose the postgres database on localhost:5432
    # ports:
    #   - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
